### ISSUE TITLE
Scale the damage

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#10]
It would be awesome if you deal more damage when you're big vs. normal - small - tiny, or damage less when you're tiny vs. small - normal - big .  🤔

**Comment by necauqua** [comment]
Yeah, but for being big thats too OP, and for small its like disabling damage at all.
And also minimum point of health is half-heart (maybe in the game its counted in floating point numbers, need to check) so what you deal when you're 1/16? zero?

Possibly I'll do a config similar to fall damage.

**Comment by LaytonBaccea** [comment]
Yes i see, that's op.  I thought of this: When you're calibrating yourself from 1/2 - 1/32,  you deal half a heart less by each stage? 🤔 
Or when you calibrate to bigger sizes?...

**Comment by HateOnCheeseCake** [comment]
Isn't this place for reporting issues...?

**Comment by LaytonBaccea** [comment]
I was told that you can use it for future updates or discussions too

**Comment by necauqua** [comment]
> Isn't this place for reporting issues...?

Feature requests are issues too and I am totally ok with that.
They are even great for being a todo list, I've seen people open issues on their own repos.

**Comment by necauqua** [comment]
Closed by e68acb5
