### ISSUE TITLE
Minecraft crash while starting

### ISSUE THREAD

**Issue by Ohri1234** [necauqua/chiseled-me#103]
When I try to use this mod minecraft doesn't start.

Log-file:

[debug.log](https://github.com/necauqua/chiseled-me/files/6303957/debug.log)

**Comment by Nomaxice** [comment]
You are using an outdated version of Chiseled Me, update to the "alpha" version 3.0.0.0-git* available on Curse.

**Comment by necauqua** [comment]
no info and likely reporter fixed his issue by upgrading to the git version
