### ISSUE TITLE
Cool idea! Bigger players can pick up smaller players and...

### ISSUE THREAD

**Issue by Salvation725** [necauqua/chiseled-me#11]
Okay so it would be really cool if normal sized players could pick up smaller players and for big players to pick up normal sized players. Perhaps being able to place them down, throw them, or place them on your head or shoulder! This would be amazing!

**Comment by LaytonBaccea** [comment]
I agree with Anton. that you shouldn't be able to place or sit on others shoulders or 
heads when you're tiny = too much work.  but perhaps in the future?! 🤔 
The other two things - crabbing and throwing,  those would be great 😉 

Edit:  Forgot to write ''place them down''  too. Added ''= too much work.  but perhaps 
in the future?! 🤔'' @Salvation725

**Comment by Salvation725** [comment]
And placing down the player safely too hopefully so you don’t always kill them? 😅 right?

Also what i meant by the shoulder and head thing is that the player who picks you up presses a button to rest the smaller person on their shoulder and the smaller person can jump off anytime they want, its more of a traveling gimic for smaller players

**Comment by Salvation725** [comment]
@laytonbaccea theoretically you could just have someone mounted as a sitting or minecart position and then just attach it to an entity that rests on players hitboxes or something among those lines. Gulliver mod did it amazingly

**Comment by LaytonBaccea** [comment]
> @LaytonBaccea theoretically you could just have someone mounted as a sitting or minecart position and then just attach it to an entity that rests on players hitboxes or something among those lines. Gulliver mod did it amazingly

Yeah i see your idea...   but it's Anton who's makin' it, so i don't know  😉

**Comment by Salvation725** [comment]
Anton clearly has the talent to do so with the features hes done so far, theres no doubt in my mind he can pull it off, its just a matter if he wants to or not. Either way I’ll still love the mod. Also he should add hotkeys for growing and shrinking! @laytonbaccea

**Comment by necauqua** [comment]
Well it would be great if I at least made riding when you and the entity are of the same size
Different sizes - need to try it out
Also I spend on average like an 1-2 hours a week (well, in bursts of 4-8 once in a month) working on the mod, so yeah

**Comment by LaytonBaccea** [comment]
@Salvation725 Yeah i asked him earlier, and he added it to the ''to-do list''  (keybinding for shrinking and growing)

**Comment by Salvation725** [comment]
Well thats a fantastic start for the riding! Also I want to thank you for putting in so much time and effort into this mod, you not only work hard on it, but you also pay attention to the criticism and ideas of your fans of the mod, so thank you for working so hard on my favorite mod! Good luck with everything!

**Comment by Salvation725** [comment]
@necauqua

**Comment by necauqua** [comment]
Ok picking up players is definitely not something that will ever climb out of the bottom of the todo list given it has the lowest priority, so I am closing this and saying that this feature is very unlikely to ever be implemented.

Will try to at least do riding at some point.
