### ISSUE TITLE
Incompatible with Fluidlogged API

### ISSUE THREAD

**Issue by freopt** [necauqua/chiseled-me#112]
https://github.com/jbredwards/Fluidlogged-API/issues/74

**Comment by necauqua** [comment]
Hello
My mod dev is currently kind of dormant (I am ukrainian, and even without that there are.. periods), but even when it's not - I don't spend much time on the mod either and all of my focus is on 1.16 version (which was aaaaalmost like ready for beta releases in february).

That means that 1.12 version is pretty much dead sadly.<br>
If you really need this fixed, you can remove [those lines](https://github.com/necauqua/chiseled-me/blob/e5ce41646b52aafe604f1a13ccab88f8aa996776/src/main/java/dev/necauqua/mods/cm/mixin/WorldMixin.java#L40-L50) and compile the mod yourself, the funny thing is that those lines do not exist in 1.16 as they are a fix for 1.12 freaking out a little when your size is less than 1.

If you don't think that you can compile it yourself I suggest you ask someone on discord, they'll help

**Comment by jbredwards** [comment]
I took care of this from my end, this issue can be closed
