### ISSUE TITLE
The mod isnt up to date....

### ISSUE THREAD

**Issue by thohag1243** [necauqua/chiseled-me#13]
i wanted to have the mod in the 1.12.2 version but the mod isnt up to date so i cant....

please fix

yours truly

ThohagYT#4351 (discord)

**Comment by HateOnCheeseCake** [comment]
And this is an issue because?
The mod creator is currently (or planning) to work on the update, a reminder like this doesn't do much.
Just checking around the comments of the page would have shown that.

**Comment by necauqua** [comment]
Closing as duplicate, heheh
But yeah, as I've said somewhere, I am planning to fix 1.11 and do at least 1.12 this summer
