### ISSUE TITLE
Clipping distance is not multiplied in new versions

### ISSUE THREAD

**Issue by necauqua** [necauqua/chiseled-me#15]
Nobody made an issue about this yet so I do it myself to keep track of what is fixed or needs to be fixed.

Cloud renderer resets the z-near distance and when you small and look directly into a wall it does not redner.
Can be fixed if you disable clouds

**Comment by LaytonBaccea** [comment]
Ohh... i haven't noticed that bug/glitch, else i would have mentioned it in here ;)
