### ISSUE TITLE
I can't use this Mod with OptiFine (1.10.2)

### ISSUE THREAD

**Issue by AlbusSilente** [necauqua/chiseled-me#16]
I tried to use all OptiFine versions for 1.10.2, but none of these worked. Please, help me to solve this problem, because I need to use OptiFine!
Thanks,
AlbusSilente

p.s. All other Mods that I use are all 100% compatibles.

**Comment by necauqua** [comment]
Well, I've said this before, but OptiFine just like this mod changes the rendering bytecode in some way somewhere.
So these two mods are obviously not compatible, I am sorry.

And yes, it is probably possible to work around and I will even try to do so in the future, but this is definitely not a priority right now.

**Comment by necauqua** [comment]
Not closing this issue so that some day it will be fixed too, yeah

**Comment by Mxcrider** [comment]
pls could you fix this soon? it is half a year later :(

**Comment by necauqua** [comment]
Well I tried to communicate my schedule for working on this mod as widely as possible, but I'll repeat it here just for you (you're not even the issue author btw):
After the end of June (just a week left btw) I will finally have a lot of free time where I will be able to work on the mod and will be fixing those issues and even then updating it to newer game vesions too.

And you can follow the [twitter](https://twitter.com/necauqua) or join [Discord](https://discord.com/invite/pZrbJNb) for questions and updates, yeah
I even wrote about it on Curse too

**Comment by Hecze** [comment]
si porfavor,es urgente,mi minecraft va a 2 fps sin optifine :(

**Comment by necauqua** [comment]
A notice:
Optifine completely and fully works with the discord beta that soon will be publicly released hopefully.

**Comment by necauqua** [comment]
Fixed in ede2651
