### ISSUE TITLE
Growing creatures

### ISSUE THREAD

**Issue by SonicJDF** [necauqua/chiseled-me#17]
I don't know exactly what caused it but I'll try and explain what happened. I had a lan server and was playing with a friend, My friend left and I used the command /kill on myself which caused all mobs to instantly turn to there normal size. I tried to change there size back but I couldn't change there size at all. The next day when I did the world again there size was back to the small size.

**Comment by necauqua** [comment]
De-sync of some sort(entity sizes were reset only on client, relogging would have fixed it), possibly already fixed because I did some rework on that stuff already

**Comment by buckted** [comment]
they're*

**Comment by necauqua** [comment]
srsly?

But also a little update - I redid/fixed some of the networking so this really might be fixed
