### ISSUE TITLE
Unknown bug.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#18]
I don't know how it does it. Every time my friend (He was the host) tried to calibrate entitys (Minimize them), they move to the right corner of the map and goes through every single (They do not on the surfaces) block untill they die or despawn. The bug do go away when restarting the server

**Comment by LaytonBaccea** [comment]
Idk how and what we did to make it happend

**Comment by necauqua** [comment]
Yeah, I experienced it too a couple of times, dont know how to reproduce it either :)

**Comment by LaytonBaccea** [comment]
Well, we hope that you can make this mod perfect in the end :D

**Comment by SonicJDF** [comment]
Hey, if it helps it seems that the baby pigs go FASTER when smaller

**Comment by necauqua** [comment]
Closing this issue as very-very stale, and a mod has changed a lot over this time, so feel free to reopen (or make a new one) it if needed
