### ISSUE TITLE
Giant mode bug

### ISSUE THREAD

**Issue by buckted** [necauqua/chiseled-me#19]
Everytime i try to walk if i'm 2 size bigger, i get teleported up 10 blocks, and if it's 32 times bigger, i just get teleported like -6000 blocks and i'm starting to die.

Can someone help me?

**Comment by LaytonBaccea** [comment]
I dont know that bug 🤔  i have never encountered it. Perhaps Anton can fix it

**Comment by necauqua** [comment]
duplicate of #2
