### ISSUE TITLE
Crash during ASM transformations

### ISSUE THREAD

**Issue by brisingraerowing** [necauqua/chiseled-me#22]
[Game Log](https://gist.github.com/BrisingrAerowing/6cb4237df379b98a39e5f8499c8cb48d)

This caused a hang on startup.

v2.0.0.1

**Comment by necauqua** [comment]
Well, that is a lot of mods.

I would be super grateful if you pinpointed which one of them causes the issue.
You can use binary search - remove half of the mods and if does not crash then conflicting mod is in the removed half and vise versa, repeat until least possible conflicting set is found.

I will be revising mod compatibility issues, but this is a coremod and it can always clash with other coremods (and you have a bunch of those too).

**Comment by brisingraerowing** [comment]
I'll take a look.

**Comment by LaytonBaccea** [comment]
I have the same issue.
When me and my friends try to add this mod to our big modpack, it crashes instantly.
We have tried different versions of the same version for mc (1.12.2)

**Comment by brisingraerowing** [comment]
@LaytonBaccea What's your mod list? I can find the intersection of it and my mod list and narrow down possible culprits.

**Comment by necauqua** [comment]
While from that crashlog I suspect that it might actually still crash for you, I suggest you to try out the latest discord beta which is very different now.
Closing this as stale, feel free to reopen or make a new issue if you need to.
