### ISSUE TITLE
Break speed should scale with the square of your size, not your size

### ISSUE THREAD

**Issue by AlaraBread** [necauqua/chiseled-me#27]
I think that the players break speed does not scale fast enough.

Currently, digging tunnels while large is horrendously slow, and digging tunnels while small is too fast.

In other words, instead of making the break speed o(n), make it o(n^2)

**Comment by necauqua** [comment]
Really?
Well I'll look into that (actually physically makes sense to make it cubic because you dig a volume), but we're not really looking into realism as much as we are into comfort gameplay

**Comment by necauqua** [comment]
Ok idk what kind of tools you were using, but digging tunnels while small is pretty slow.

I decided to leave things as is for now, maybe more complicated mechanics (e.g. breaking 2x2x2 of blocks when you're 2x the size) will be considered in the future

**Comment by necauqua** [comment]
Yes more than a year later, huh
