### ISSUE TITLE
Antipolarized Concentrated Pym Essence Recipe.

### ISSUE THREAD

**Issue by AlaraBread** [necauqua/chiseled-me#28]
The antipolarized concentrated pym essence recipe takes effect whenever two items that are not already a recipe are placed into a crafting bench.

1. Open a crafting bench
2. Place two items into it in a way that should not craft anything.
3. Antipolarized Concentrated Pym Essence will appear in the output slot

Expected behavior
Nothing will be in the output slot

Screenshots
![Screenshot from 2020-01-11 20-02-05](https://user-images.githubusercontent.com/59781761/72212630-67949a00-34ad-11ea-91cc-d12bf834c492.png)
![Screenshot from 2020-01-11 20-02-16](https://user-images.githubusercontent.com/59781761/72212631-67949a00-34ad-11ea-94e4-2409cdda609c.png)

Additional information:
- Installed mods: Chiseled-Me, Chisels and bits
- Forge version: 14.23.5.2847
- Mod version: 2.0.0.1

**Comment by necauqua** [comment]
Whow, yes, I once heard about this but never checked.
Thanks for the detailed report, will be fixed asap

**Comment by necauqua** [comment]
> asap

Yeah didn't really work out, but soon I will do a lot of work with this mod, as I've said in a lot of places.
