### ISSUE TITLE
Scale at which distance mobs notice the player

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#3]
Hi Anton.
I have played your mod to test it for a while, and really look up to you getting the mod functioning as good as it can get.  I also love the new fixes you applied lately!! , keep up the tremendous work

But if it could be possible....   could you make the AIs on all Mobs and Monsters incabable of seeing the player when calibrated to a certain sizes?  (as in from 1/32 and down all the way to 1/4096)

**Comment by necauqua** [comment]
Yeah, I'll add that to the list

**Comment by LaytonBaccea** [comment]
Sounds great

**Comment by LaytonBaccea** [comment]
Sorry....  clicked on close issue by accident

**Comment by necauqua** [comment]
In the ~~discord beta~~ my unreleased code that soon will be the latest discord beta, the `EntityAITarget` class (which is the base AI task that mobs use to target the player) has scaled distances, so if you are really small you need to stand closer to the mobs position than it's hitbox would allow you to, so this feature is effectively done.

And if you are just a little small, you will need to be closer to the mob for it to see you. It uses a geometric average of your and mobs size, so it should work both ways.

**Comment by necauqua** [comment]
Fixed in ede2651
