### ISSUE TITLE
iChun Util. Conflict

### ISSUE THREAD

**Issue by Pie-Not-Lie** [necauqua/chiseled-me#31]
Couldn't find the fml-latest.log, but here's the crash log file. Game crashes on loading screen.
[debug.log](https://github.com/necauqua/chiseled-me/files/4081971/debug.log)

**Comment by necauqua** [comment]
Yeah looks like fml-latest.log was renamed to debug.log, the content is exactly what I need.

iChunUtil is already like at the top of the mods to check mod compat, still thanks for reporting though.

Maybe I'll do something to make that list public or something (like a new issue template I guess)

**Comment by necauqua** [comment]
not sure if the exact duplicate exists, will recheck all the crash issues when making the template and stuff
