### ISSUE TITLE
Particles and Effects

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#33]
Is it a stupid idea with this possible feature?:  Can become immune to any effects when calibrated to atom size. 🤔 
I thought of it when i played with MutedGalaxy on my server, we tried different sizes with monsters and tried to shoot arrows and throw bottles with effects at them and ourselfs...

**Comment by necauqua** [comment]
idk, will take a look

this is pretty easy todo so I may add this and make it configurable

**Comment by necauqua** [comment]
Ok I took a look and I don't think that being immune to potion effects when being small is reasonable.
And sizes below 1/16 were made just for fun, they are pretty useless anyway imo.
