### ISSUE TITLE
Game Crash even with all other mods removed

### ISSUE THREAD

**Issue by savvymarcom** [necauqua/chiseled-me#34]
I started to remove mods to find which one was causing the issue, but then when all mods were removed the game still crashed. 

Crash log attached
[crash-2020-03-08_11.56.24-client.txt](https://github.com/necauqua/chiseled-me/files/4303153/crash-2020-03-08_11.56.24-client.txt)

**Comment by necauqua** [comment]
This is caused by an old Forge version, you can update it to fix that
