### ISSUE TITLE
Broken Metamorph hitboxes (try entities from other mods)

### ISSUE THREAD

**Issue by Snapshotlight** [necauqua/chiseled-me#35]
**Describe the bug**
When you play this mod with Metamorph and other mods, some hitboxes of some creatures seem strange when you morph into them such as Mutant Zombie in Mutant Beasts and most engender mobs in The Engender. Their hitbox changed into the player hitbox. However, if you set their size to 0, their hitbox become normal again. I don't know if Moprh will work strangely.

**To Reproduce**
1.Open the creative morph menu with F3+B on.
2.Morph into some creatures, and you will find the error.

**Expected behavior**
Their Hitbox should be as big as normal.

**Screenshots**
N/A

I am sorry that I can't find the fml files and I have forgot these informations. But this error actually happened.

**Comment by necauqua** [comment]
Holy shit, it even not to crash with Morph?
I will check that of course, but I promise nothing as this is a hitbox changing coremod, and Morph changes hitboxes too.
They are inherently incompatible unless I (or iChun, which is unlikely) hardcode something in to prevent these kinds of bugs.
As I've said though, I'll look into it at some point)

**Comment by necauqua** [comment]
> if you set their size to 0

Sounds kind of weird ngl. Anyway I will look into that (as I've already said some months ago)

**Comment by necauqua** [comment]
Ok I fixed how they update hitbox, since vanilla entities were affected too I never tested it with mod entities, but unless they do something dumb that I am not fixing anyway, everything should be fine now
