### ISSUE TITLE
Multiplayer walk speed glitch with Inventory Pets mod installed

### ISSUE THREAD

**Issue by MinecrafterDaOne** [necauqua/chiseled-me#41]
Me and my friend are playing Minecraft forge 1.12.2 multiplayer, and every now and again, the view bobbing stops working and then when I changed my size to 1/16 my walk speed did not change, I believe this is Mod Argument. Do you of anything that causes this bug?

**Comment by MinecrafterDaOne** [comment]
from what I know it only happens in multiplayer

**Comment by necauqua** [comment]
Yeah, sounds like a desync of some kind.
When I get back to working on this mod I'll take a look at a lot of stuff so this one might be fixed as well then.
Also if you find the way to reproduce the bug it will be so much easier for me to try to fix it too.
Anyway, thanks for your input.

**Comment by MinecrafterDaOne** [comment]
Update:
this happens with the Inventory Pets mod installed, Usually with the cloud pet in your survival inventory

**Comment by necauqua** [comment]
This is super good news, thanks
(well you understood that by good news I meant that it will be so much easier for me to find and fix this knowing when exactly this happens, not that the other mod breaks it huh)

**Comment by necauqua** [comment]
Pfew, while they made not the best development decisions while making their mod, this was marginably easier than #65

And yeah the mod itself is cool, but not its code lol
