### ISSUE TITLE
Updates and 1.12.2 support?

### ISSUE THREAD

**Issue by AlienXtream** [necauqua/chiseled-me#45]
i know this is a bit of a big ask and all but given that 1.12.2 is the current main modding version (with 1.14 slowly picking up) can we expect the major features/bug fixes to be backported to this version?

**Comment by necauqua** [comment]
> current main modding version

well I kinda thought to go for updates up to 1.15 and stick with them, but okay, maybe I'll support the 1.12 version for some time

Anyway this mod at the very least needs not to crash with like every other mod, so I will work on that (and not version updating) first.

**Comment by necauqua** [comment]
Closed as answered question.
You can go to Discord to ask and discuss more, github issue format is not the best for that

**Comment by AlienXtream** [comment]
yeh. my discord is really cluttered so i tend to only bother joining them if i spend a LOT of time communicating. as it is i will likely not have much else that needs adding.

as for the updates and 1.12 v 1.15, i was mainly thinking the same for it at least being stable and more a less compatible with the major mods (morph/ichun util might be a problem but the 1.12 version if that is alpha and has its own problems) in that they dont crash on startup or on shrinking. circumstantial crashes can be worked around so long as they dont corrupt saves. and by major features i mean like BIG things that you personally feel warrant backporting (for example the 1/16th speed flight. bee may/may not be included). this is a little off the topic of the question but heck, you might not even NEED to implement your own flight if you can simply make it correctly slow vanilla flight speed while tiny XD

**Comment by AlienXtream** [comment]
anyway, sorry for such messy posts. i just want to take a moment to thank you and many who've come before you for your contributions to the MC community. this game would literally be nothing like it is were it not for people like you making awesome content (and all for free to boot) for this game. its not said enough and it needs to be acknowledged more that minecraft isnt just Mojang's game, but all of ours. i tip my hat to you sir and bid you well :)

**Comment by necauqua** [comment]
I am pretty sure that if the mod launches without crashes, there is no way it can corrupt worlds

**Comment by AlienXtream** [comment]
if it "shrinks" the player and triggers a crash but just happens to auto save at the same moment you are shrinking then you will load into the game and the shrinking events will happen, triggering a crash before a player can reasonably do anything. at least in theory. such cases would be EXTREMELY rare but need to be considered sometimes. even so, its good practice to backup anything important to you, even non minecraft things, but a failsafe of some sort (an emergency repair config setting for instance to "try" and fix crashing errors) is something to keep in mind. best way to make something work well is to make it idiot proof, then break it some more ;)

**Comment by necauqua** [comment]
k, got you
By 'corrupting the world' I meant when data is lost, like player inventory or chunks got deleted or something.

In your scenario you can uninstall the mod (well, that gets rid of mod items, eh) or use some nbt editor and remove the resizing field from player nbt to fix stuff

**Comment by AlienXtream** [comment]
yeh, world broken and cant get in. fail safe would basically do exactly that. purge all your mods data attributes without actually having to remove the mod. more a convenience for the end user/for people who are not so technically inclined to be able to do that. easier to say to them "go to your config and change 'emergency repair' (or whatever you might call it) to 'true' and see if that helps" than going through what would basically become an NBTEdit tutorial. choice is yours, im just some guy on the internet throwing my 2 cents into the pile :P
