### ISSUE TITLE
Creative flight system

### ISSUE THREAD

**Issue by AlienXtream** [necauqua/chiseled-me#46]
a creative flight like mechanism that is tailored to the reduced scale to allow easier building "big" things. something like a "bee on a string" or something, with a little bee flying around and the player on a string under it. imo it has the "vanilla" style about it, like the carrot on a stick, so it fits even in a mostly vanilla environment without really feeling out of place :D

**Comment by AlienXtream** [comment]
i just had the idea pop into my head while thinking about the mod and thought "i need to share this idea" :)

**Comment by necauqua** [comment]
Well I'll think about something to help build things in creative, but I'll see if it would be a bee on a string or something else, thanks)

**Comment by necauqua** [comment]
That is because what I've pictured in my head when I've read that is a bit hard to implement, but if you mean like an item (similar to carrot on a stick) - then maybe. Although again, this is a 'tech' mod, so vanilla vibes might feel out of place themselves, we'll think.

**Comment by AlienXtream** [comment]
yeh, i can understand that. implementation wise i was thinking more enable creative flight, slow player to 1/16 (or whatever scaling factor is used) default speed and basically render a bee and a harness on the player. like, a chest plate with a custom model that is the string and bee. as for the "vanilla" thing. i was meaning more in that it fits in with the vanilla style of things, like the comedy and "silliness" of some of its features. it just feels like it would fit, you know. especially with 1.15 being all about bees and all. was just a funny idea i had that i felt was worth sharing. 

i mean, technically, using the extra bit manipulation mod i COULD just BUILD the "chestplate" and stick it on XD. but yeh. wasn't thinking an animated bee flying around, just a chestplate with a custom static model, perhaps with an animated wing texture to give the illusion of movement.

**Comment by necauqua** [comment]
Oh, you meant to enable creative flight in survival when you're small, now I get it.
Yes, seems reasonable, when I'll finally work on the mod I'll do something like you have described.

Although I still think that since this is a tech mod, you should use some "hi-tech device" for that and not some vanilla-like stuff.
However, the whole mod content will be revised so I might give vanilla-like style a go

**Comment by AlienXtream** [comment]
dont be strict with it. if you wanna go non vanilla like thats fine. as mentioned, i just felt the idea of a bee suspending the player from a little string was funny and had the same vibe as vanilla humor XD

**Comment by necauqua** [comment]
Ok I actually have a really neat idea for allowing faster travel when being small, however it does not include creative-like flight, and likely nothing like this will be added, so I am closing this issue as part of my great GitHub issues cleanup.
