### ISSUE TITLE
Crash with BetterFPS

### ISSUE THREAD

**Issue by MarkColo2** [necauqua/chiseled-me#48]
BetterFPS - crashed on 14.23.6.2854 - (log attached)
----------------------------------
BetterFps-1.4.8.jar
chiseled-me-1.12.2-2.0.0.1.jar

[Chiseled-me, BetterFPS crash.log](https://github.com/necauqua/chiseled-me/files/4772946/Chiseled-me.BetterFPS.crash.log)

**Comment by MarkColo2** [comment]
Was trying to add chiseled-me to a Hexxit 1.12.2 pack that I got from Twitch.  Did some binary searching to narrow the incompatibility down to this mod.  Did my testing with only the two mods above and caused the crash.

**Comment by necauqua** [comment]
Oof, might be same as with OptiFine - some rendering incompatibility, there is a probability of it being unfixable (well, I mean hard enough to fix to not bother trying).
Will check anyway.
