### ISSUE TITLE
Crash with VanillaFix

### ISSUE THREAD

**Issue by MarkColo2** [necauqua/chiseled-me#49]
VanillaFix - crashed on 14.23.6.2854 - (log attached)
----------------------------------
chiseled-me-1.12.2-2.0.0.1.jar
VanillaFix-1.0.10-99.jar

[Chiseled-me, VanillaFix Crash.log](https://github.com/necauqua/chiseled-me/files/4772952/Chiseled-me.VanillaFix.Crash.log)

**Comment by MarkColo2** [comment]
Was trying to add chiseled-me to a Hexxit 1.12.2 pack that I got from Twitch.  Did some binary searching to narrow the incompatibility down to this mod.  Did my testing with only the two mods above and caused the crash.

**Comment by necauqua** [comment]
Really good - well, not the crash, but the fact that you put the effort, thanks.
Will check, test and fix when I get to do a lot of work after end of June (as I've said everywhere already).

**Comment by necauqua** [comment]
Eh, might be same as with fps thing and OptiFine.
And also Quark maybe messes with stuff too.
So that's not really surprising that they crash with this mod, since I mess with stuff all over the place - to make the effect stable and realistic.
Will check everything anyway, maybe will find workarounds for some stuff, yeah

**Comment by MarkColo2** [comment]
No worries.  I know how nice it is to have a tiny focused test environment with extraneous things removed.  The community appreciates what you do to keep mods like this alive.

**Comment by AlienXtream** [comment]
^

**Comment by necauqua** [comment]
Partially fixed since in the current master (unreleased) it does not crash but the player camera is broken

**Comment by necauqua** [comment]
Completely fixed in discord beta btw

**Comment by necauqua** [comment]
Fixed in ede2651
