### ISSUE TITLE
No recipe for the 1 scale?

### ISSUE THREAD

**Issue by MakerTim** [necauqua/Chiseled-Me#5]
Or JEI is hating me and not showing it; but i think there is no go back to scale 1 recipe... intended?
you can use one up, or die... but can the back to 1 scale be craftable?

**Comment by necauqua** [comment]
Oh, i should've mentioned it more loudly (or add JEI tooltip).
You can get this thing by 'depleting' any of the recalibrators.
When you use them when your size is the same it wastes more charges, so this shouldn't be too much clicking.
