### ISSUE TITLE
Pushing me away from a one block hole when flying in it

### ISSUE THREAD

**Issue by CreeperGuy72192** [necauqua/chiseled-me#50]
So what happens is when I'm trying to enter a one block hole if I fly up it pushes me to one the side of the block. The other mods I have are Chisel, Chisel & Bits, Fakename, More Player Models, SecretRoomsMod, WorldEdit, ConnectedTexturesMod and that's it. I tried using the mod by itself but it was still happening and I don't know why I haven't changed anything I literally tried using it by itself. I have the newest version of each mod for 1.12.2. My Forge Version is forge-14.23.5.2854

![Minecraft 1 12 2 6_28_2020 1_50_45 PM](https://user-images.githubusercontent.com/65190117/85954735-809fe300-b947-11ea-8e13-952ede8520e3.png)

I'm being pushed away in that image

![Minecraft 1 12 2 6_28_2020 1_51_27 PM](https://user-images.githubusercontent.com/65190117/85954736-84cc0080-b947-11ea-872c-64e3d09e7914.png)

I'm not pushed away when just standing in the one block hole. I've had this happen before but I don't know why.
[latest.log](https://github.com/necauqua/chiseled-me/files/4842760/latest.log)
I think that's the log. Also ignore that it said Aphmau was playing that was the fakename mod. It happens when I go about halfway up the block. It also happens when I go halfway up and I'm not flying.

**Comment by CreeperGuy72192** [comment]
It happens when I go about halfway up the block.

**Comment by necauqua** [comment]
Looks like a desync for me - on the server your size must be bigger
If you relog then you are back to size 1, right?
Anyway the mod is about to have a lot of stuff rewritten, so this may or may not persist

**Comment by CreeperGuy72192** [comment]
I'm playing on a singleplayer world and if I leave and enter the world again my size is still the same size I was when I left.

**Comment by necauqua** [comment]
Aha, then literally idk, this is weird
As I am saying in a lot of places, I'll be rewriting major parts of the mod so your exact case might or might not persist

**Comment by necauqua** [comment]
> singleplayer world

doesn't matter, there is an integrated server running in singleplayer too and so client/server desync's are very possible in this game/

**Comment by CreeperGuy72192** [comment]
Oh I forgot that it was still a integrated server and the first time I was having the problem was when I used 1.10.2 and was using this mod and LittleTiles mod because I didn't know UpAndDownAndAllAround didn't work with the mod but I know now, I made a empty box and I started having that problem but didn't have it for a while after it happened and it is happening again. I'll just wait for you to rewrite the mod and I'll try to see if it still happens.

**Comment by necauqua** [comment]
Yeah I am having a ton of free time starting literally tomorrow (will idle for a couple of days more ofc), come [discord](https://discord.gg/pZrbJNb) for news and talk if you need it

**Comment by CreeperGuy72192** [comment]
Ok
