### ISSUE TITLE
Player, when smaller, takes damage from lava just from being near it

### ISSUE THREAD

**Issue by Stecca6663** [necauqua/chiseled-me#55]
**Description**

When the player is at size 0.2 or smaller he takes damage when being near lava or when being near lava with a block above the lava.

**To reproduce**

To reproduce it just set your size at 0.2 or smaller and go near lava.

**Expected behavior**

You should be able to stay near lava without dying (like you can when you are normal size).

**Video**(Because you can't really tell with a screenshot)
Here's a small video about this bug: https://youtu.be/6Qom2ftJFVA

**Additional information:**
- Forge version: 1.12.2-14.23.5.2847
- Mod version: chiseled-me-1.12.2-2.0.0.1

If you need more infos, don't hesitate to ask!

**Comment by LorenzoPapi** [comment]
confirmed in mixin-fixed version, if it can help, the exact size from which you take damage is 0.222222216427 (yes, I have some free time lol and yes I love this mod)

**Comment by necauqua** [comment]
I dont think that the _exact_ size would help me much but thanks for the effort :)
