### ISSUE TITLE
Model not visible when in 3rd person in small sizes

### ISSUE THREAD

**Issue by LorenzoPapi** [necauqua/chiseled-me#56]
**Describe the bug**
When your size is less than 3.051758E-4 (approximated), your model in 3rd person gets invisble

**To Reproduce**
1. Start Minecraft with chiseled me
2. Create/Load a world
3. Use the sizeof command or use the 1/4096 recalibrator
4. See that you're not visible and neither the hitbox is

**Expected behavior**
You shoud be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/42911751/88511475-27c67780-cfe5-11ea-9286-0bed04968b8f.png)
here I am visible
![image](https://user-images.githubusercontent.com/42911751/88511544-49bffa00-cfe5-11ea-8327-0afc9859389c.png)
here I am not

**Additional information:**
- Installed mods: just chiseled me
- Forge version: 1.12.2-14.23.5.2854
- Mod version: 2.0.0.2 - mixin working version
- `fml-latest.log` file: *I didn't find it lol*

**Comment by necauqua** [comment]
Well, cannot reproduce (and even failed to reproduce back then, you know), please retry with the latest discord beta, the mod has changed a lot

**Comment by LorenzoPapi** [comment]
Ok

**Comment by LorenzoPapi** [comment]
it was fixed
