### ISSUE TITLE
valkryien skies and possibly engender mod crash

### ISSUE THREAD

**Issue by ntck** [necauqua/chiseled-me#60]
Valkyrien Skies crashes on loading world (also potentially engender mod)
[crash-2020-08-27_11.32.19-client.txt](https://github.com/necauqua/chiseled-me/files/5133485/crash-2020-08-27_11.32.19-client.txt)

[debug.log](https://github.com/necauqua/chiseled-me/files/5133474/debug.log)

**Comment by necauqua** [comment]
No crash happens with those two mods in the latest beta (and a couple of dozens of others), implying accidental fix (a lot has changed since this issue was opened).
Feel free to open another issue if you encounter crashed with the new beta (which is finally soon to be released on curse).
