### ISSUE TITLE
Optifine+Dynamic Lights=Crash

### ISSUE THREAD

**Issue by Stecca6663** [necauqua/chiseled-me#61]
When I use chiseled me and optfine while dynamic lights are set on fast or fancy, the game crashes. This happens when I create a world or after a few seconds from entering the world. If you need more info, I'll try to provide them!

**Additional information:**
- Forge version: 14.23.5.2854
- Chiseled me version: 2.1.0.0-beta
- Crashlog file: [crashlog.txt](https://github.com/necauqua/chiseled-me/files/5135748/crashlog.txt)
- Debug.log file: [debug.log](https://github.com/necauqua/chiseled-me/files/5135744/debug.log)

**Comment by necauqua** [comment]
Fixed in discord beta btw

**Comment by necauqua** [comment]
Nah discord beta closes like half of the issues there but they stay open until I push a commit (so for like a week more idk)

**Comment by necauqua** [comment]
Fixed in ede2651
