### ISSUE TITLE
LLibrary crash

### ISSUE THREAD

**Issue by aDreamEater** [necauqua/chiseled-me#62]
When I try to use this mod with mod library LLibrary, the game crashes on load. 
Chiseled Me and LLibrary are the only mods in use.
Both of them individually work fine, but fail in combination.
[crash-2020-09-03_22.50.02-client.txt](https://github.com/necauqua/chiseled-me/files/5172423/crash-2020-09-03_22.50.02-client.txt)

**Comment by necauqua** [comment]
This exact error is fixed in the current discord beta

**Comment by necauqua** [comment]
Fixed in ede2651
