### ISSUE TITLE
Customnpc hitbox weirdness

### ISSUE THREAD

**Issue by Catlord-3** [necauqua/chiseled-me#65]
Custom npcs npcs do not properly scale using recalibrators

**To Reproduce**
1. Create an npc using custom npcs
2. Use a volume recalibrator on them (due to their interact feature you need to be like 5 blocks away to do this)
3. Us f3+b to see broken hitbox (upon resizing back to normal hitbox is still broken, its larger but not correct)

I tested and this is not a visual issue, this is their actual hitbox.

**Expected behavior**
Customnpcs would scale like all other mobs

**Screenshots**
![2020-09-16_13 39 03](https://user-images.githubusercontent.com/69657737/93390194-2ca7ea80-f822-11ea-8a3f-c1205ecd8981.png)
![2020-09-16_13 38 48](https://user-images.githubusercontent.com/69657737/93390208-30d40800-f822-11ea-8891-092230f8955e.png)

**Additional information:**
- Installed mods: customnpcs and chiseled me
- Forge version: Latest version
- Mod version: 2.1 beta

**Comment by Catlord-3** [comment]
A note: they both have the same nbt data exactly, except for the size change. they are clones of each other.

**Comment by necauqua** [comment]
> same nbt data exactly

So a relog should fix it I guess.


Well customnpc has some weird setSize interactions I even do recall knowing about something like that somehow.
Will check and possibly fix

**Comment by necauqua** [comment]
Was a crude fix for their weird custom hitbox stuff, but then I went full ~re..~ ocd and also fixed shadows, name height and gui rendering.

Note that big CustomNPC entites will often not be rendered - but this is a weird CustomNPC bug (happens to size 1 entities too) that I have no idea how to fix nor I really want to.
