### ISSUE TITLE
When repeatedly changing size, the player jitters a lot.

### ISSUE THREAD

**Issue by CosmicCrowMC** [necauqua/chiseled-me#66]
**Describe the bug**
When changing size, you're unable to move properly, if at all.

**To Reproduce**
1. Set up a repeating command block with the command "/sizeof @p multiply 0.9999" (or a number very close to 1)
2. Set the command block to "always active", close the command block menu and try moving around, especially in the air.

**Expected behavior**
To change size without stuttering. The expected behavior happens in 1.12.2.2.0.0.1.

(Can't really post a screenshot, but I can send a clip on the Discord if you need.)

**Additional information:**
- Installed mods: Chiseled Me, Optifine 1.12.2_HD_U_F5
- Forge version: 1.12.2-14.23.5.2838
- Mod version: 1.12.2.2.1.0.0-beta

**Comment by necauqua** [comment]
Ok this one is like **very** hard to fix, tried multiple times and never succeeded yet, but obviously this is a severe bug and I will keep trying.

**Comment by necauqua** [comment]
Fixed in ede2651
