### ISSUE TITLE
Minecraft 1.16.4

### ISSUE THREAD

**Issue by ZStr10** [necauqua/chiseled-me#72]
Доброго дня!

Ви плануєте оновлювати мод до 1.16.4?

Дякую!

**Comment by necauqua** [comment]
Планирую конечно, вот только сначала нужно дочинить 1.12 и потом ещё всё что между ними - это займёт кучу-кучу времени, к сожалению.

github issues не для таких общих вопросов, советую зайти в [дискорд](https://discord.necauqua.dev) (он правда почти польностью на инглише), там есть бета 1.12 с кучей фиксов которую я никак не выложу на curse, и плюс апдейты тоже туда в первую очередь летят.
