### ISSUE TITLE
[1.12.2] Server sleeping warp error

### ISSUE THREAD

**Issue by Sora-Canstavia** [necauqua/chiseled-me#74]
When you sleep in a bed (so the screen greys out and skips night) when you wake up, every time you use the shrinking or growing items you will be warped back to your bed until you relog. 

Video here: https://www.youtube.com/watch?v=CK_dl4ue8rI&feature=youtu.be
Switched to creative due to taking some damage and using up charges showing and testing this ^^;

**Comment by necauqua** [comment]
Fixed in ede2651
