### ISSUE TITLE
[1.12.2] Ghast, Blaze, wither and fire charge projectiles not working in multiplayer

### ISSUE THREAD

**Issue by Sora-Canstavia** [necauqua/chiseled-me#75]
When any of these are fired off they immediately act as if they have hit something, but do no damage. Arrows, ender dragon attacks, other modded projectiles seem to work, though.

**Comment by Sora-Canstavia** [comment]
Update: Shulker projectiles also do not function serverside

**Comment by necauqua** [comment]
Fixed in ede2651
