### ISSUE TITLE
Something I really feel you need

### ISSUE THREAD

**Issue by EliteWolfVR** [necauqua/chiseled-me#78]
I want to have feature *X* in the mod.
- A list of compatible and incompatible mods.

Why do I think the feature *X* needs to be added (optional).
- Many people (including myself) have issues with figuring out what mods work with chiseled me, although, I'm not asking you to make this, I'm asking if you'd allow me to make a list for you, using as many popular forge mods possible in 1.12, and testing them with chiseled me (I'm incredibly bored and feel like helping). Please consider allowing me to do this for the project.

**Comment by necauqua** [comment]
Uh, ok, I allow, sure
Not like I can disallow, huh
I suggest you to go speak with some active people in the [discord](https://discord.necauqua.dev) for that, they want to do the same so you can help each other.

And well I want the mod to be more compatible - and the beta that is only awailable in discord so far is much better with that already, so make sure to consider that

Anyway I am closing that as it does not really fit github issues, and I got your point.

**Comment by EliteWolfVR** [comment]
yea sorry, didnt think about asking in discord, I'm also really glad you let me because I've already started

**Comment by EliteWolfVR** [comment]
yea sorry, didnt think about asking in discord, I'm also really glad you let me because I've already started
