### ISSUE TITLE
[1.12.2] Rendering error with Crayfish Furniture Mod

### ISSUE THREAD

**Issue by Sora-Canstavia** [necauqua/chiseled-me#79]
**Describe the bug**
When you sit in a sittable object from the Mr Crayfish's Furniture Mod with Chiseled Me installed, a big white block appears around your character in said object, it's only visible while you're sitting there, making it a non-issue for singleplayer but a pretty glaring graphical error in multiplayer.

**To Reproduce**
1. Install Chiseled Me
2. Install Crayfish Furniture Mod
3. Sit in any object that allows you to sit on it from CFM (chair, sofa/couch etc)

**Expected behavior**
Not to have a big white block appear over you when sitting down

**Screenshots**
https://cdn.discordapp.com/attachments/708757460890026086/796435318232055918/unknown.png Without CFM installed

https://cdn.discordapp.com/attachments/708757460890026086/796436119410966548/unknown.png With CFM Installed

**Additional information:**
- Installed mods: Far too many, as you know, however it happens as well with just Crayfish Furniture Mod and Chiseled Me, with no other mods along side it
- Forge version: 14.23.5.2854
- Mod version: Latest beta of CM and latest available of CFM for 1.12.2
[debug.log](https://github.com/necauqua/chiseled-me/files/5777432/debug.log)

Provided Debug log for the large modpack, as I'd already deleted the instance with just CM and CFM ^^;

**Comment by necauqua** [comment]
Fixed in ede2651
