### ISSUE TITLE
You can't damage others when tiny or big.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#8]
When you are tiny versus normal other living things, or the other way around, you can't recieve damage when they step on you, or when you step on them - You just get pushed away.

**Comment by necauqua** [comment]
Yeah, this one added to the list, but not at the highest priority.

**Comment by LaytonBaccea** [comment]
Okay sounds great 😉

**Comment by necauqua** [comment]
Can you actually clarify what do you mean by that?
Is this a bug (cant damage) or a feature request (make it so that cant damage)?
More info pls :)

**Comment by necauqua** [comment]
Superseeded by (your issue too btw) #10

**Comment by necauqua** [comment]
Oh wait this was a bug, I thought that was a feature request - reach distance for entity interactions was fixed even in the latest actual release I think, and the beta should be even better than that.
