### ISSUE TITLE
Mod just crashes by itself

### ISSUE THREAD

**Issue by EnderCreeper21** [necauqua/chiseled-me#81]
I load the mod, game crashes.
[crash-2021-01-16_09.03.47-client.txt](https://github.com/necauqua/chiseled-me/files/5824595/crash-2021-01-16_09.03.47-client.txt)

**Comment by LorenzoPapi** [comment]
Update forge version

**Comment by necauqua** [comment]
^ that, or use the discord beta which has this fixed anyway
