### ISSUE TITLE
Server crash with Chiseled Me 

### ISSUE THREAD

**Issue by GithubBreen** [necauqua/chiseled-me#82]
I'm using PloudOS (free hosting service) and when server is online, it immediately stops. At first I was using the mod with
Chisels & Bits and tested it out. Only Chiseled Me crashes the server. 

Crash Report:
https://pastebin.com/q860r1bC

Server version: 1.12.2

**Comment by LorenzoPapi** [comment]
1) to fix, update forge version
2) in the discord server there is a beta that fixes lots of crashes and errors

**Comment by necauqua** [comment]
Known, fixed in non-beta by updating forge, just fixed in beta for any forge
