### ISSUE TITLE
Where is the integration package or jar file?

### ISSUE THREAD

**Issue by Aether-254** [necauqua/chiseled-me#87]
Where is the _integration package_ or _jar file_?
I can't find the _jar file_, and I don't know the _integration package_ at where.

**Comment by necauqua** [comment]
What?

Well there are jar files [here](https://www.curseforge.com/minecraft/mc-mods/chiseled-me/files) and [here](https://github.com/necauqua/chiseled-me/releases).
If you want the beta that was built from the last commit, it is in the discord server, [here](https://discord.com/invite/pZrbJNb)

**Comment by Aether-254** [comment]
Ok, Thank you
