### ISSUE TITLE
Projectiles and damage glitches when tiny.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#9]
Idk if anyone else experinced it.
But when i calibrate myself to 1/1026 - 1/4096, my arrows/firecharges/projectiles glithces, from 
vanilla and other mods.

And the same happens with melee damage.
When i'm tiny and monsters too, Monsters can damage me by the range 
of 1-4 bits = I can't reach and kill them.

**Comment by necauqua** [comment]
Nothing I could really do with that - as you can see in my other answer, at these sizes floating point rounding errors and other various glitches begin to occur.
The 1/4096 size was made just for fun, the main puprose of this mod is 1/16 and everything still works mostly ok at 1/256

**Comment by LaytonBaccea** [comment]
Aahh okay :D
