### ISSUE TITLE
Specific sounds breaking and unable to play discs when present

### ISSUE THREAD

**Issue by Shibva** [necauqua/chiseled-me#93]
**Describe the bug**
after having narrowed things down, I have found that this mod seems to be responsible in me not being able to play music discs and to further add to this, I believe this mod is also preventing some sound events happening (ex: Blaze shooting SFX dosent play yet can be played via command)

**To Reproduce**
1. Create a new world
2. place a jukebox
3. place in any minecraft disk (modded or vanilla, both will cause this issue)
4. (optional) summon a blaze and have it attack you

**Expected behavior**
all sound events should be playing and that music discs can be played 

**Screenshots**

**Additional information:**
- Installed mods: 
[modlist.zip](https://github.com/necauqua/chiseled-me/files/5992167/modlist.zip)
this should contain the links to the mods in the provided document

- Forge version: 1.12.2 14.23.5.2855
- Mod version: chiseled-me-1.12-3.0.0.0-git-3af10ac
- `minecraft_profile_folder/logs/debug.log` file: *providing this is highly recommended*

**PLEASE REFRAIN FROM POSTING GIANT WALLS OF TEXT, USE ANY KIND OF PASTEBIN, GIST OR JUST A PLAIN TEXT FILE**

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/108133325-60619780-7082-11eb-9270-b42a86675db6.png)
here is some other ones that dint get uploaded for some reason

**Comment by Shibva** [comment]
and heres the configs for the pack, You will need them 
[use me.zip](https://github.com/necauqua/chiseled-me/files/5992272/use.me.zip)

**Comment by necauqua** [comment]
Do you seriously expect me to download 257+12 mods one by one to test this?
It does not happen with just my mod.
If you 'narrowed things down' you should've given the _minimal_ list of mods that this happens with.

I kind of know why this may happen, but this is still some kind of really weird mod interaction and having a couple of mods this happens with instead of an enormous modpack would be feasible to check

**Comment by Shibva** [comment]
if you can provide me wht mods you think might have this strange interaction, I could remove them on my end to check

but yeah, I can give it a shot

**Comment by necauqua** [comment]
Actually good for you I am 99% certain I found what caused this lol
I will upload a possibly fixed beta to discord so you can check
