### ISSUE TITLE
player camera not working properly 

### ISSUE THREAD

**Issue by somedudeonline** [necauqua/chiseled-me#95]
**Describe the bug**
camera height not changing with playermodel as i resize myself

**To Reproduce**
1. Go to minecraft
2. Use use any matter volume recalibrator
3. the speed and actual player size do change but the camera stays in place as if i were the same size

**Expected behavior**
expect the camera to change with the player size when using the matter volume recalibrators
**Screenshots**
![Minecraft 1 12 2 3_9_2021 10_10_06 AM](https://user-images.githubusercontent.com/58888059/110494565-bba30a80-80c1-11eb-8562-2415a9041626.png)
![Minecraft 1 12 2 3_9_2021 10_09_59 AM](https://user-images.githubusercontent.com/58888059/110494600-c1005500-80c1-11eb-96fe-83c9b6e0d4a1.png)
[2021-03-09-1.log.gz](https://github.com/necauqua/chiseled-me/files/6109563/2021-03-09-1.log.gz)

**Additional information:**
- Installed mods: https://drive.google.com/file/d/1u8E14NigxUjJn_yJK5K4XOVlfoMiIrVx/view?usp=sharing
- Forge version: forge 1.12.2-forge-14.23.5.2854
- Mod version: 1.12.2-2.0.0.1
- `minecraft_profile_folder/logs/debug.log` file: *providing this is highly recommended*

**PLEASE REFRAIN FROM POSTING GIANT WALLS OF TEXT, USE ANY KIND OF PASTEBIN, GIST OR JUST A PLAIN TEXT FILE**

**Comment by necauqua** [comment]
Caused by galacticraft ~~being stupid~~, fixed in the curse alpha (you are using the curse release version).
