### ISSUE TITLE
Crashes due to "java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer"

### ISSUE THREAD

**Issue by Vararg97** [necauqua/chiseled-me#99]
When I try to use this mod with mods chisel and bits and morph mod, the game crashes. 

"java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer" is the error message and the exit code is 255. I've tried using a few different versions off of the curseforge page.

**Comment by Vararg97** [comment]
If anyone needs it here is the crash log file and the game output.

Crash Log File:

[crash-2021-03-23_10.01.44-client.txt](https://github.com/necauqua/chiseled-me/files/6191555/crash-2021-03-23_10.01.44-client.txt)

Game Output:

`10:01:44.048
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
10:01:44.049
10:01:44.049
| State | ID             | Version      | Source                        | Signature                                |
10:01:44.049
|:----- |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
10:01:44.058
| L     | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
10:01:44.058
| L     | mcp            | 9.42         | minecraft.jar                 | None                                     |
10:01:44.058
| L     | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
10:01:44.058
| L     | forge          | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
10:01:44.058
| L     | chiseled_me    | 2.0.0.0      | chiseled-me-1.12-2.0.0.0.jar  | None                                     |
10:01:44.058
| L     | chiselsandbits | 14.33        | chiselsandbits-14.33.jar      | None                                     |
10:01:44.058
| L     | ichunutil      | 7.2.1        | iChunUtil-1.12.2-7.2.1.jar    | None                                     |
10:01:44.058
| L     | morph          | 7.2.0        | Morph-1.12.2-7.2.1.jar        | None                                     |
10:01:44.058
10:01:44.058
Loaded coremods (and transformers):
10:01:44.058
Chiseled Me ASM (chiseled-me-1.12-2.0.0.0.jar)
10:01:44.058
dev.necauqua.mods.cm.asm.Plugin
10:01:44.058
GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-16.0.49' Renderer: 'Intel(R) HD Graphics 6000'
10:01:44.058
Launched Version: 1.12.2-forge-14.23.5.2854
10:01:44.063
LWJGL: 2.9.2
10:01:44.063
OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-16.0.49, Intel Inc.
10:01:44.063
GL Caps: Using GL 1.3 multitexturing.
10:01:44.063
Using GL 1.3 texture combiners.
10:01:44.063
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
10:01:44.064
Shaders are available because OpenGL 2.1 is supported.
10:01:44.064
VBOs are available because OpenGL 1.5 is supported.
10:01:44.064
10:01:44.064
Using VBOs: Yes
10:01:44.064
Is Modded: Definitely; Client brand changed to 'fml,forge'
10:01:44.064
Type: Client (map_client.txt)
10:01:44.064
Resource Packs:
10:01:44.064
Current Language: ~~ERROR~~ NullPointerException: null
10:01:44.064
Profiler Position: N/A (disabled)
10:01:44.064
CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
10:01:44.603
Process crashed with exit code 255`

**Comment by necauqua** [comment]
The crashlog is from the old curse release, you sounded like you've tried the alpha (which should have like _a lot_ of stuff fixed, and notably compat with those two mods) did it not work too?

**Comment by Vararg97** [comment]
I haven't tried past 2.0.0.1 because I honestly forgot the alpha/beta list was there. I'll try it.

**Comment by necauqua** [comment]
Yeah there is like just a couple of things missing for that alpha to become a true 3.0.0.0 release, and curse is weird with how it displays alphas eh

**Comment by Vararg97** [comment]
Thanks a lot, that really got me stuck and also thanks for replying so fast. I usually shy away from posting on forums, cause I have bad memories.... Anyways thanks again.

**Comment by necauqua** [comment]
Accident, I was just on github just in that moment
There are a ton of nice people in discord who know all the basic issues, next time you can ask there :)
